Feature/users endpoint
574BandOfBrothers/memoriae-api pull request #6
Opened 2017-11-15 18:51 UTC by mustafagonul

2017-11-15 20:50 UTC, ardaogulcan commented
test this please

2017-11-16 15:36 UTC, ardaogulcan requested changes

2017-11-16 15:36 UTC, ardaogulcan commented on src/models/users.js
> +module.exports = mongoose.model('users', userSchema);
burada users'ı User olarak değiştirelim

2017-11-16 20:18 UTC, mustafagonul commented
- Tests are done manually by now. 
- I will add tests later.
- Collection name is changed from **users** to **User**. Cpp habits :)

@ardaogulcan

2017-11-16 20:39 UTC, ardaogulcan approved these changes

2017-11-16 20:39 UTC, ardaogulcan commented
LGTM

2017-11-16 21:05 UTC, merged